spring:

  redis:
    host: localhost
    port: 6379
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: admin
